=== onap/aai-search-data-service/search-data-service-app/src/main/resources/json/schema/analyzer.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Analyzer",
  "description": "The analyzer aggregates a tokenizer and multiple filters to describe how an input stream should be indexed.",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "behaviours": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tokenizer": {
      "type": "string"
    },
    "filters": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== onap/aai-search-data-service/src/test/resources/json/analysis-config.json
[
  {
    "name": "nGram_analyzer",
    "description": "NGram Analyzer",
    "tokenizer": "whitespace",
    "filters": [
      "lowercase",
      "asciifolding",
      "nGram_filter"
    ]
  },
  {
    "name": "whitespace_analyzer",
    "description": "Whitespace Analyzer",
    "tokenizer": "whitespace",
    "filters": [
      "lowercase",
      "asciifolding"
    ]
  }
]
